# -*- coding: utf-8 -*-
"""Zhuang-ABCA-1 Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpBLpGIY5xauIu6pjCYd9v0AhBcZpsZ3

# **Phase 1: Setup & Installation**
"""

# Install the Allen toolkit for streamlit
import subprocess
import sys

def install():
    subprocess.check_call([sys.executable, "-m", "pip", "install", "abc_atlas_access[notebooks] @ git+https://github.com/alleninstitute/abc_atlas_access.git"])

# Call the function
install()

# Install the analysis tools
!pip install scanpy squidpy

"""# **Phase 2: Data Acquisition (All Metadata)**"""

import pandas as pd
import anndata
import scanpy as sc
import squidpy as sq
from pathlib import Path
import warnings

# This is the corrected import line:
from abc_atlas_access.abc_atlas_cache.abc_project_cache import AbcProjectCache

# Suppress common warnings to keep things clean
warnings.simplefilter("ignore")

# 1. Set up the data cache (where to save files)
# This will create a folder called 'abc_data' in your current directory
download_base = Path("abc_data")
abc_cache = AbcProjectCache.from_cache_dir(download_base)

# We'll use the 'Zhuang-ABCA-1' dataset
DATASET_NAME = 'Zhuang-ABCA-1'
CCF_NAME = 'Zhuang-ABCA-1-CCF'
TAXONOMY_NAME = 'WMB-taxonomy'
CCF_ATLAS_NAME = 'Allen-CCF-2020'

print("Downloading metadata files...")

# 2. Download all the "map legend" files we need
try:
    # File 1: The main cell list (x,y coords, cell ID number)
    cell_meta_df = abc_cache.get_metadata_dataframe(
        directory=DATASET_NAME,
        file_name='cell_metadata'
    )
    cell_meta_df = cell_meta_df.set_index('cell_label')

    # File 2: The cell type "decoder ring" (e.g., 14939 = 'Astrocyte')
    cluster_details_df = abc_cache.get_metadata_dataframe(
        directory=TAXONOMY_NAME,
        file_name='cluster_to_cluster_annotation_membership_pivoted'
    )
    # --- THIS LINE IS NOW CORRECTED ---
    cluster_details_df = cluster_details_df.set_index('cluster_alias')

   # File 3: The 3D anatomical "address" for each cell
    ccf_coords_df = abc_cache.get_metadata_dataframe(
        directory=CCF_NAME,
        file_name='ccf_coordinates'
    )

    # --- ADD THIS LINE TO FIX THE ERROR ---
    # Rename the conflicting columns to 'x_ccf', 'y_ccf', 'z_ccf'
    ccf_coords_df.rename(columns={'x': 'x_ccf', 'y': 'y_ccf', 'z': 'z_ccf'}, inplace=True)
    # --- END OF FIX ---

    ccf_coords_df = ccf_coords_df.set_index('cell_label')

    # File 4: The anatomical "decoder ring" (e.g., 1009 = 'CA1')
    parcellation_df = abc_cache.get_metadata_dataframe(
        directory=CCF_ATLAS_NAME,
        file_name='parcellation_to_parcellation_term_membership_acronym'
    )
    parcellation_df = parcellation_df.set_index('parcellation_index')
    # Rename columns to be clear
    parcellation_df.columns = [f"parcellation_{col}" for col in parcellation_df.columns]

    # File 5: The gene "decoder ring" (e.g., 'ENSMUSG...' = 'Gfap')
    gene_df = abc_cache.get_metadata_dataframe(
        directory=DATASET_NAME,
        file_name='gene'
    )
    gene_df = gene_df.set_index('gene_identifier')

    print("All metadata files downloaded and loaded!")

except Exception as e:
    print(f"An error occurred during download. Please check your internet connection.")
    print(f"Error details: {e}")

"""# **Phase 3: Build the "Master Metadata Table"**"""

print("Building the 'Master Metadata Table'...")

# 1. Join cell list with cell type names
# This matches the 'cluster_alias' number (e.g., 14939) to its name (e.g., 'Astro-TE NN')
master_meta = cell_meta_df.join(cluster_details_df, on='cluster_alias')

# 2. Join with the 3D anatomical coordinates
# This adds the 'parcellation_index' (the anatomical ID number)
master_meta = master_meta.join(ccf_coords_df)

# 3. Join with the anatomical names
# This matches the 'parcellation_index' (e.g., 1009) to its name (e.g., 'CA1')
master_meta = master_meta.join(parcellation_df, on='parcellation_index')

print(f"Master table built for {len(master_meta)} cells.")
print("\n--- Example of what's inside the Master Table ---")

# Show only the most important columns
# We use .get(['...', '...']) to avoid errors if a column is missing
print(master_meta.get(['x', 'y', 'subclass', 'parcellation_structure']).head())

"""# **Phase 4: Filter for Hippocampus (CA1 & DG)**"""

print("Filtering for Hippocampus (CA1 & DG) cells...")

# We filter using the 'parcellation_structure' column, which has the official brain atlas names.
# 'CA1|DG' means "find any cell where the 'parcellation_structure' column contains 'CA1' OR 'DG'"
# 'na=False' tells pandas to treat any empty (NaN) values as "not a match"
filter_mask = master_meta['parcellation_structure'].str.contains('CA1|DG', na=False)

# Apply the filter to create our new, smaller "hippocampus-only" metadata table
hip_metadata = master_meta[filter_mask]

print(f"Finished filtering.")
print(f"Original cells: {len(master_meta)}")
print(f"Found {len(hip_metadata)} cells in CA1 or DG regions.")

# This is the important check:
print("\n--- Unique anatomical regions we found ---")
# This should print a list like ['DG', 'CA1', 'CA3'] (if CA3 was included, etc.)
print(hip_metadata['parcellation_structure'].unique())

"""# **Phase 5: Final Project AnnData Object**"""

print("Loading the 3GB gene expression file (this may take a minute)...")

# 1. Get the path to the 3GB file
expression_file_path = abc_cache.get_data_path(
    directory=DATASET_NAME,
    file_name=f"{DATASET_NAME}/log2"
)

# 2. Load the giant file in "backed" mode
adata_full = anndata.read_h5ad(expression_file_path, backed='r')

print(f"Full dataset loaded in 'backed' mode: {adata_full.shape[0]} cells")

# 3. Get the list of cell IDs (the index) from our small hippocampal table
hippocampal_cell_ids = hip_metadata.index

# 4. Create our NEW, SMALL AnnData object!
# --- THIS IS THE CORRECTED LINE ---
# We use .to_memory() to load our slice into RAM
adata_hip = adata_full[hippocampal_cell_ids, :].to_memory()

# 5. Add all our metadata (from Phase 4) to the object
adata_hip.obs = hip_metadata

# 6. Add the 2D spatial coordinates (this is ESSENTIAL for Squidpy)
# We use the 'x' and 'y' from the original metadata, NOT the 'x_ccf', 'y_ccf'
adata_hip.obsm['spatial'] = hip_metadata[['x', 'y']].values

# 7. Add the gene names
adata_hip.var = gene_df.loc[adata_hip.var.index]
# Set the .var_names to the human-readable gene_symbol
adata_hip.var_names = gene_df.loc[adata_hip.var.index]['gene_symbol'].values

# 8. Clean up (closes the big 3GB file)
adata_full.file.close()
del adata_full

print("\n--- Project AnnData Object Created! ---")
print(f"Our project now has {adata_hip.n_obs} cells and {adata_hip.n_vars} genes.")
print("\nThis is our final object for analysis:")
print(adata_hip)

"""# **Phase 6:Cell Types & Check Genes**"""

print("Checking our gene panel...")

# Get the list of all available gene names from our new object
available_genes = list(adata_hip.var_names)

# Our "wish list" of genes we want to find
gene_wish_list = [
    # Cell Types
    'Gfap', 'P2ry12', 'Apoe', 'C1qa', # Glia
    'Slc17a7', 'Gad1', 'Pvalb', 'Sst', # Neurons

    # Mallach et al. Pathways (The key to our project!)
    'Slc6a11', # Astrocyte GABA Transporter
    'Slc1a3', 'Gls', # Astrocyte Glutamate Transporters
    'Gabbr2', 'Gria4' # Neuron Receptors
]

genes_we_HAVE = [gene for gene in gene_wish_list if gene in available_genes]
genes_we_are_MISSING = [gene for gene in gene_wish_list if gene not in available_genes]

print(f"\nWe HAVE these {len(genes_we_HAVE)} key genes: {genes_we_HAVE}")
print(f"\nWe are MISSING these {len(genes_we_are_MISSING)} genes: {genes_we_are_MISSING}")
print("\nWe will proceed with the genes we HAVE.")

"""# **Phase 7a: Main Analysis (Combined Heatmap & Z-Scores)**"""

print("Finding all available cell type names in the 'subclass' column...")

# Get all unique names from the 'subclass' column
all_cell_types = adata_hip.obs['subclass'].unique()

print("\n--- All Available Subclass Names ---")
print(all_cell_types)

# Let's try to find the ones we care about
# We'll print any name that contains "Astro", "Micro", "Sst", or "Pvalb"
print("\n--- Suggested Names for Your List ---")
for name in all_cell_types:
    if 'Astro' in name or 'Micro' in name or 'Sst' in name or 'Pvalb' in name:
        print(name)

"""# **Phase 7b: Main Analysis(Neighborhood Analysis)**"""

print("Running Analysis: Cell Type Neighborhoods...")

# --- This list is now filled with the REAL names from our output ---
target_cell_types = [
    # Astrocytes (from your output)
    '319 Astro-TE NN',
    '318 Astro-NT NN',
    '321 Astroependymal NN',
    '320 Astro-OLF NN',

    # Microglia (from your output)
    '334 Microglia NN',

    # Sst Interneurons (from your output)
    '053 Sst Gaba',
    '056 Sst Chodl Gaba',

    # Pvalb Interneurons (from yourV output)
    '052 Pvalb Gaba',
    '051 Pvalb chandelier Gaba',

    # Excitatory Neurons (from your 'All' list)
    '016 CA1-ProS Glut', # CA1 Excitatory
    '017 CA3 Glut',      # CA3-type Excitatory
    '037 DG Glut'        # DG Excitatory
]
# --- End of List ---


# Create a 'mask' to find all cells that are in our target list
analysis_mask = adata_hip.obs['subclass'].isin(target_cell_types)

# Create a final, small AnnData object just for this analysis
adata_final = adata_hip[analysis_mask, :].copy()

# This check should now show a positive number!
print(f"Filtered for {len(adata_final)} cells of our target types.")

# --- THIS IS THE NEW LINE TO FIX THE ERROR ---
# Convert the 'subclass' column to the 'categorical' data type
adata_final.obs['subclass'] = adata_final.obs['subclass'].astype('category')
# --- END OF FIX ---


# --- NOW WE RUN THE ANALYSIS ---
if len(adata_final) > 1:
    # 1. Build the spatial graph (finds all neighboring cells)
    print("Building spatial neighborhood graph...")
    sq.gr.spatial_neighbors(adata_final, coord_type="generic")

    # 2. Run the neighborhood test
    print("Running neighborhood enrichment test...")
    sq.gr.nhood_enrichment(adata_final, cluster_key="subclass")

    # 3. Plot the result!
    # This is your first major figure.
    # Red = Attract (friends), Blue = Repel (strangers)
    print("\nPlotting Figure 1: Cell Type Neighborhoods Heatmap")
    sq.pl.nhood_enrichment(
        adata_final,
        cluster_key="subclass",
        cmap="coolwarm",
        title="Hippocampal Cell Type Neighborhoods (CA1 & DG)"
    )

    print("\n--- Project Complete! ---")
else:
    print("\n--- ERROR ---")
    print("Still 0 cells found. This is strange.")
    print("Please double-check the names in the 'target_cell_types' list for any typos.")

"""# **Phase 7c: Main Analysis( Spatial Map of Cell Types)**

# **Phase 7d: Main Analysis(Gene Expression Map)**
"""

print("Plotting Figure 3: Gene Expression Maps")

# We can plot multiple genes. We know we HAVE 'Pvalb' and 'Gfap'.
genes_to_plot = ['Pvalb', 'Gfap']

# Use the same plotting function, but color by gene expression
# 'cmap="viridis"' makes it a "heat" map (yellow = high, purple = low)
sq.pl.spatial_scatter(
    adata_final,
    color=genes_to_plot,   # Color by our list of genes
    shape=None,
    size=0.5,
    cmap="viridis",       # Use a 'heat' colormap
    title="Gene Expression for Pvalb and Gfap"
)

"""# **Visual (Cell Type Counts)**"""

import seaborn as sns
import matplotlib.pyplot as plt

print("Plotting Figure 4: Cell Type Counts")

# Set the size of the figure
plt.figure(figsize=(10, 8))

# Use seaborn to create a horizontal bar chart
sns.countplot(
    data=adata_final.obs,
    y="subclass",                  # Put the cell types on the y-axis
    order=adata_final.obs['subclass'].value_counts().index # Sort by most common
)

plt.title('Cell Type Counts in our Hippocampal Dataset (n = 65,956)')
plt.xlabel('Number of Cells')
plt.ylabel('Cell Subclass')
plt.show()

"""# **Visual (Spatial Map)**"""

import matplotlib.pyplot as plt
import scanpy as sc # Make sure scanpy is imported

print("Creating your final multi-panel figure...")

# 1. Create a figure with two subplots, side-by-side
# We make the t3otal figure wide (figsize=(20, 8))
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

# --- Panel A: The "Where Are They?" Map (Using Scanpy) ---
# We use scanpy's spatial plot function
sc.pl.spatial(
    adata_final,
    color="subclass",        # Color the dots by their cell type
    spot_size=5,             # Adjust spot size as needed (scanpy uses different scaling)
    title="Panel A: Spatial Map of Cell Types",
    ax=ax1,                  # Tell it to draw on the first axis
    show=False,              # Don't show the plot yet
    legend_loc=None          # Turn off the legend for this panel to save space
)
ax1.set_aspect('equal') # Ensure correct aspect ratio

# --- Panel B: The "Who Likes Whom?" Heatmap (Squidpy is fine here) ---
# We use the 'ax=ax2' argument to tell squidpy to draw on our second subplot
sq.pl.nhood_enrichment(
    adata_final,
    cluster_key="subclass",
    cmap="coolwarm",
    title="Panel B: Cell Type Neighborhoods (Attraction/Repulsion)",
    ax=ax2,                  # Tell it to draw on the second axis
    show=False               # Don't show the plot yet
)

# 3. Clean up and show the final combined figure
plt.tight_layout() # Makes the plots fit nicely
plt.show()

print("\n--- Your final summary figure is complete! ---")

"""# **Cell for CA1 vs DG Comparison**"""

import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt

print("Splitting data into CA1 and DG subsets...")

# --- Split Data ---
# Create boolean masks for CA1 and DG based on the parcellation structure
ca1_mask = adata_hip.obs['parcellation_structure'].str.contains('CA1', na=False)
dg_mask = adata_hip.obs['parcellation_structure'].str.contains('DG', na=False)

# Create the separate AnnData objects
adata_ca1 = adata_hip[ca1_mask].copy()
adata_dg = adata_hip[dg_mask].copy()

print(f"Created CA1 subset with {len(adata_ca1)} cells.")
print(f"Created DG subset with {len(adata_dg)} cells.")

# --- Define the target cell types list AGAIN (important!) ---
# Use the same list as before
target_cell_types = [
    '319 Astro-TE NN', '318 Astro-NT NN', '321 Astroependymal NN', '320 Astro-OLF NN', # Astrocytes
    '334 Microglia NN', # Microglia
    '053 Sst Gaba', '056 Sst Chodl Gaba', # Sst Interneurons
    '052 Pvalb Gaba', '051 Pvalb chandelier Gaba', # Pvalb Interneurons
    '016 CA1-ProS Glut', '017 CA3 Glut', '037 DG Glut' # Excitatory Neurons
]

# --- Function to Run and Plot Enrichment ---
# This avoids repeating code
def analyze_region(adata_region, region_name):
    print(f"\n--- Analyzing {region_name} ---")

    # Filter for target cell types
    analysis_mask = adata_region.obs['subclass'].isin(target_cell_types)
    adata_filt = adata_region[analysis_mask, :].copy()

    # Conversion of  subclass to categorical
    adata_filt.obs['subclass'] = adata_filt.obs['subclass'].astype('category')

    print(f"Filtered for {len(adata_filt)} cells.")

    if len(adata_filt) > 1:
        # Build graph
        print("Building spatial graph...")
        sq.gr.spatial_neighbors(adata_filt, coord_type="generic")

        # Run enrichment
        print("Running neighborhood enrichment...")
        sq.gr.nhood_enrichment(adata_filt, cluster_key="subclass")

        # Plot heatmap
        print(f"Plotting {region_name} Heatmap...")
        fig, ax = plt.subplots(1, 1, figsize=(10, 8)) # Create a new figure/axis
        sq.pl.nhood_enrichment(
            adata_filt,
            cluster_key="subclass",
            cmap="coolwarm",
            title=f"{region_name} Cell Type Neighborhoods",
            ax=ax # Plot on the created axis
        )
        plt.show() # Show the plot for this region
    else:
        print(f"Not enough cells found in {region_name} for analysis.")

# Analysis for CA1 ---
analyze_region(adata_ca1, "CA1")

# Analysis for DG ---
analyze_region(adata_dg, "Dentate Gyrus (DG)")

print("\n--- CA1 vs DG Comparison Complete ---")

"""# **Combined Cell: Analysis & Z-Score Extraction**"""

print("Running Combined Analysis: Neighborhoods & Z-Scores...")

# --- Define Target Cell Types ---
target_cell_types = [
    '319 Astro-TE NN', '318 Astro-NT NN', '321 Astroependymal NN', '320 Astro-OLF NN', # Astrocytes
    '334 Microglia NN', # Microglia
    '053 Sst Gaba', '056 Sst Chodl Gaba', # Sst Interneurons
    '052 Pvalb Gaba', '051 Pvalb chandelier Gaba', # Pvalb Interneurons
    '016 CA1-ProS Glut', '017 CA3 Glut', '037 DG Glut' # Excitatory Neurons
]

# --- Filter Data ---
analysis_mask = adata_hip.obs['subclass'].isin(target_cell_types)
adata_final = adata_hip[analysis_mask, :].copy()
print(f"Filtered for {len(adata_final)} cells.")

# --- Prepare for Analysis ---
if len(adata_final) > 1:
    # Convert subclass to categorical
    adata_final.obs['subclass'] = adata_final.obs['subclass'].astype('category')

    # --- Run Neighborhood Analysis ---
    print("Building spatial graph...")
    sq.gr.neighbspatial_ors(adata_final, coord_type="generic")

    print("Running neighborhood enrichment...")
    sq.gr.nhood_enrichment(adata_final, cluster_key="subclass")

    # --- Plot Heatmap ---
    print("\nPlotting Figure 1: Combined Cell Type Neighborhoods Heatmap")
    fig, ax = plt.subplots(1, 1, figsize=(10, 8))
    sq.pl.nhood_enrichment(
        adata_final,
        cluster_key="subclass",
        cmap="coolwarm",
        title="Hippocampal Cell Type Neighborhoods (Combined CA1 & DG)",
        ax=ax
    )
    plt.show()

    # --- Extract Z-Scores ---
    print("\nExtracting Z-scores...")

    results_key = "subclass_nhood_enrichment"
    if results_key in adata_final.uns:
        enrichment_results = adata_final.uns[results_key]
        z_scores = enrichment_results['zscore'] # This is a NumPy array

        # --- THIS IS THE NEW FIX ---
        # Get the list of cell types in the correct order
        category_names = list(adata_final.obs['subclass'].cat.categories)

        # Create a "decoder ring" (dictionary) to get the numerical index for each name
        name_to_index = {name: i for i, name in enumerate(category_names)}
        # --- END OF FIX ---

        # --- Define pairs based on your combined heatmap ---
        pairs_to_check = [
            ('319 Astro-TE NN', '037 DG Glut'),    # Astro vs DG Neuron
            ('334 Microglia NN', '037 DG Glut'),   # Microglia vs DG Neuron
            ('319 Astro-TE NN', '318 Astro-NT NN'), # Astro vs Astro
            ('319 Astro-TE NN', '334 Microglia NN') # Astro vs Microglia
        ]

        print("\n--- Z-Scores for Specific Cell Pairs ---")
        for cell1, cell2 in pairs_to_check:
            try:
                # Use the decoder ring to get the numerical positions
                idx1 = name_to_index[cell1]
                idx2 = name_to_index[cell2]

                # Use the numbers to access the array
                score = z_scores[idx1, idx2]

                interpretation = ""
                if score > 2: interpretation = "(Significant Attraction)"
                elif score < -2: interpretation = "(Significant Repulsion)"

                print(f"{cell1} vs {cell2}: Z-score = {score:.2f} {interpretation}")

            except KeyError as e:
                print(f"Error finding pair: {cell1} or {cell2}. Check names. Missing: {e}")
        print("\n--- Project Complete! ---")

    else:
        print("\n--- ERROR ---")
        print("Neighborhood enrichment results still not found after running.")

else:
    print("\n--- ERROR ---")
    print("Filtered dataset has too few cells.")

"""# **Robustness Check ( Varying Neighbor Parameters )**"""

print("Running Robustness Check (n_neighbors=5 and n_neighbors=45)...")

# --- Define Target Cell Types (Use the same list as before) ---
target_cell_types = [
    '319 Astro-TE NN', '318 Astro-NT NN', '321 Astroependymal NN', '320 Astro-OLF NN', # Astrocytes
    '334 Microglia NN', # Microglia
    '053 Sst Gaba', '056 Sst Chodl Gaba', # Sst Interneurons
    '052 Pvalb Gaba', '051 Pvalb chandelier Gaba', # Pvalb Interneurons
    '016 CA1-ProS Glut', '017 CA3 Glut', '037 DG Glut' # Excitatory Neurons
]

# --- Function to run analysis with different n_neighbors ---
def run_robustness_check(n_neighbors_value):
    print(f"\n--- Testing with n_neighbors = {n_neighbors_value} ---")

    # We need to `  use a fresh copy of adata_hip to build the graph
    analysis_mask = adata_hip.obs['subclass'].isin(target_cell_types)
    adata_test = adata_hip[analysis_mask, :].copy()
    adata_test.obs['subclass'] = adata_test.obs['subclass'].astype('category')

    if len(adata_test) > 1:
        # 1. Building spatial graph with the NEW neighbor value
        print("Building spatial graph...")
        sq.gr.spatial_neighbors(adata_test, n_neighs=n_neighbors_value, coord_type="generic")
        # --- END OF FIX ---

        # 2. Running enrichment
        print("Running neighborhood enrichment...")
        sq.gr.nhood_enrichment(adata_test, cluster_key="subclass")

        # 3. Ploting heatmap
        print(f"Plotting heatmap for n_neighbors = {n_neighbors_value}")
        fig, ax = plt.subplots(1, 1, figsize=(10, 8))
        sq.pl.nhood_enrichment(
            adata_test,
            cluster_key="subclass",
            cmap="coolwarm",
            title=f"Neighborhoods (n_neighbors = {n_neighbors_value})",
            ax=ax
        )
        plt.show()
    else:
        print("Error: Not enough cells.")

# --- Run the check for k=5 and k=45 ---
# Note: k=5 might be too sparse, but it's a good test.
run_robustness_check(n_neighbors_value=5)
run_robustness_check(n_neighbors_value=45)

print("\n--- Robustness Check Complete ---")

"""# **Cell: Clustermap of Heatmap**"""

import numpy as np # Import numpy for inf handling

print("Running Clustermap analysis...")

# --- Get the Z-score results from your original run ---
results_key = "subclass_nhood_enrichment"
if results_key in adata_final.uns:
    enrichment_results = adata_final.uns[results_key]
    z_scores = enrichment_results['zscore'] # This is the NumPy array

    # Get the category names (the labels)
    category_names = list(adata_final.obs['subclass'].cat.categories)

    # --- Convert the numpy array to a labeled pandas DataFrame ---
    z_score_df = pd.DataFrame(z_scores, index=category_names, columns=category_names)

    # --- THIS IS THE NEW FIX ---
    # Replace all NaN (Not a Number) values with 0
    z_score_df.fillna(0, inplace=True)
    # Also replace any 'inf' (infinity) values with 0, just in case
    z_score_df.replace([np.inf, -np.inf], 0, inplace=True)
    # --- END OF FIX ---

    # --- Create the Clustermap (like Kim Fig. 7) ---
    print("Plotting clustered heatmap...")
    # This plot will have the Z-score numbers written in the squares
    sns.clustermap(
        z_score_df,
        cmap="coolwarm",        # Use the same color map
        center=0,               # Center the color on zero
        figsize=(12, 12),
        annot=True,             # Write the Z-score numbers in the squares
        fmt=".1f"               # Format numbers to 1 decimal place
    )
    plt.suptitle("Clustered Neighborhood Heatmap (Z-Scores)", y=1.02)
    plt.show()

else:
    print("ERROR: Results not found. Please re-run your main 'Combined Analysis & Z-Score' cell one more time to repopulate 'adata_final'.")

"""# **Post Hoc Analysis:Genetic Ontology (GO) Enrichment Analysis**"""

#Install the GO enrichment tool
print("Installing gprofiler...")
!pip install gprofiler-official

from gprofiler import GProfiler
import scanpy as sc
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

print("Running GO Enrichment...")

# --- 1. Define our "Glia-Glia Module" ---
# These are the cell types that clustered together in your clustermap
glial_module_types = [
    '319 Astro-TE NN',
    '321 Astroependymal NN',
    '318 Astro-NT NN',
    '334 Microglia NN'
]

# --- 2. Find the top genes for this module ---
# We use scanpy's 'rank_genes_groups' to find genes that are
# highly expressed in our module compared to all other cells.

# Create a copy of our final dataset to work with
adata_go = adata_final.copy()

# Create a new column 'module'
adata_go.obs['module'] = [
    'Glia_Module' if cell in glial_module_types else 'Other_Cells'
    for cell in adata_go.obs['subclass']
]
adata_go.obs['module'] = adata_go.obs['module'].astype('category')

# Run the differential expression test to find marker genes
print("Finding top genes for 'Glia_Module'...")
# We use 'raw=False' because we are working with the log2 data
sc.tl.rank_genes_groups(adata_go, groupby='module', method='wilcoxon', use_raw=False)

# Get the top genes for our module
# We take the top 150 genes with a positive log-fold change
top_genes = sc.get.rank_genes_groups_df(adata_go, group='Glia_Module')
top_genes = top_genes[top_genes['logfoldchanges'] > 0.5]
glial_gene_list = list(top_genes['names'].head(150))

print(f"Found {len(glial_gene_list)} unique marker genes for the Glial Module.")

# --- 3. Run GO Enrichment on these genes ---
if len(glial_gene_list) > 10:
    print("Running GProfiler...")
    gp = GProfiler(return_dataframe=True)
    go_results = gp.profile(
        organism='mmusculus', # 'mmusculus' is for mouse
        query=glial_gene_list
    )

    # --- 4. Plot  of Top 15 Results ---
    print("\n--- Top GO Enrichment Results for Glial Module ---")

    # Filter for just 'Biological Process' (GO:BP)
    go_bp = go_results[go_results['source'] == 'GO:BP'].head(15)

    if not go_bp.empty:
        # We plot the -log10(p-value) for better visualization
        go_bp['-log10_p_value'] = -np.log10(go_bp['p_value'])

        plt.figure(figsize=(10, 8))
        sns.barplot(
            data=go_bp,
            x='-log10_p_value',
            y='name',
            palette='viridis' # A nice color palette
        )
        plt.title("Top Biological Processes - Glial Module")
        plt.xlabel("-log10(p-value)")
        plt.ylabel("GO Term Name")
        plt.show()
    else:
        print("No GO:BP terms found.")
else:
    print("Not enough marker genes found to run GO enrichment.")

print("\n--- Functional Analysis Complete! ---")

"""# **Post Hoc Analysis: Spatial Density Correlation (Validation)**"""

# --- CELL: ADVANCEMENT 2 - SPATIAL DENSITY CORRELATION (Corrected) ---
import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np # We'll need numpy

print("Running Advancement 2: Spatial Density Correlation...")

# --- 1. Bin the tissue into a grid (Manual Method) ---
# We will use pandas.cut to create 50 bins in the x and y dimensions
n_bins = 50

# Create a copy of the obs table to work with
obs_df = adata_final.obs.copy()

# Add the x and y coordinates from obsm['spatial']
# (obsm['spatial'] is a 2-column array: [:, 0] is x, [:, 1] is y)
obs_df['x_coord'] = adata_final.obsm['spatial'][:, 0]
obs_df['y_coord'] = adata_final.obsm['spatial'][:, 1]

# Create the bins
obs_df['x_bin'] = pd.cut(obs_df['x_coord'], bins=n_bins, labels=False)
obs_df['y_bin'] = pd.cut(obs_df['y_coord'], bins=n_bins, labels=False)

# Create a unique 'grid_bin' ID for each square
obs_df['grid_bin'] = obs_df.apply(lambda row: f"{row['x_bin']}_{row['y_bin']}", axis=1)

# --- 2. Count cells per bin ---
# This creates a new table: rows are grid_squares, columns are cell_types
counts_per_bin = obs_df.groupby('grid_bin')['subclass'].value_counts().unstack(fill_value=0)

# --- 3. Calculate the Correlation ---
# We run a Pearson correlation on the counts.
correlation_matrix = counts_per_bin.corr(method='pearson')

# --- 4. Plot the Correlation Heatmap (like Kim Fig. 3) ---
print("Plotting Spatial Density Correlation Heatmap...")
plt.figure(figsize=(10, 8))
sns.heatmap(
    correlation_matrix,
    cmap="coolwarm",  # Use the same color map
    center=0,         # Center on zero
    annot=True,       # Show the correlation numbers
    fmt=".2f"         # Format to 2 decimal places
)
plt.title("Spatial Density Correlation (Regional Validation)")
plt.show()

print("\n--- Density Correlation Complete! ---")

"""# **Post Hoc Analysis: Gene High Analysis (Validation)**"""

# --- CELL: ADVANCEMENT 3 - GENE-HIGH ANALYSIS ---
import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt
import numpy as np

print("Running Advancement 3: Gene-High Analysis...")

# --- 1. Create a new AnnData object for this analysis ---
# (This assumes 'adata_final' is still in memory from your combined analysis run)
try:
    adata_gh = adata_final.copy()
except NameError:
    print("ERROR: 'adata_final' not found. Please re-run the '# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---' cell first.")
    # This will stop the code if adata_final is missing
    raise

gene_of_interest = 'Gfap'

# --- 2. Find the "Gfap_High" cells ---
# Get the 70th percentile cutoff for Gfap expression
# We use .X.toarray() in case the data is 'sparse'
cutoff_70 = np.percentile(adata_gh[:, gene_of_interest].X.toarray(), 70)

# Create boolean (True/False) masks
is_high = adata_gh[:, gene_of_interest].X.toarray().flatten() > cutoff_70
is_astro = adata_gh.obs['subclass'].astype(str).str.contains('Astro', na=False)

# --- 3. Create the new 'analysis_group' column ---
# Start by copying the original cell types
adata_gh.obs['analysis_group'] = adata_gh.obs['subclass'].astype(str)

# Re-label the astrocytes based on Gfap expression
adata_gh.obs.loc[is_astro & is_high, 'analysis_group'] = 'Astro_Gfap_High'
adata_gh.obs.loc[is_astro & ~is_high, 'analysis_group'] = 'Astro_Gfap_Low'

# Convert to categorical for squidpy
adata_gh.obs['analysis_group'] = adata_gh.obs['analysis_group'].astype('category')

print(f"Created new groups. Counts:\n{adata_gh.obs['analysis_group'].value_counts()}")

# --- 4. Run the neighborhood analysis on these NEW groups ---
print("\nBuilding new spatial graph...")
sq.gr.spatial_neighbors(adata_gh, coord_type="generic")

print("Running enrichment on Gfap-High groups...")
sq.gr.nhood_enrichment(adata_gh, cluster_key="analysis_group")

# --- 5. Plot the new, more detailed heatmap ---
print("Plotting 'Gene-High' Neighborhood Heatmap...")
# This will be a larger heatmap
fig, ax = plt.subplots(1, 1, figsize=(14, 12))
sq.pl.nhood_enrichment(
    adata_gh,
    cluster_key="analysis_group",
    cmap="coolwarm",
    title="Neighborhoods: Gfap-High vs Gfap-Low Astrocytes",
    ax=ax
)
plt.show()

print("\n--- Gene-High Analysis Complete! ---")

# --- CELL: FINAL ADVANCEMENT - GO ENRICHMENT ---

# 1. Install the GO enrichment tool
print("Installing gprofiler...")
!pip install gprofiler-official

from gprofiler import GProfiler
import scanpy as sc
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

print("Running GO Enrichment on 'Astro_Gfap_High' group...")

# --- 1. Use the 'adata_gh' object from the previous step ---
# (It already has the 'analysis_group' column)

# --- 2. Find the top genes for the 'Astro_Gfap_High' group ---
# We use scanpy's 'rank_genes_groups' to find genes that are
# highly expressed in our 'Astro_Gfap_High' group compared to all others.
print("Finding top genes for 'Astro_Gfap_High'...")

# We must convert 'analysis_group' to a string for this to work
adata_gh.obs['analysis_group'] = adata_gh.obs['analysis_group'].astype(str)

# Run the differential expression test to find marker genes
# We use 'raw=False' because we are working with the log2 data
sc.tl.rank_genes_groups(adata_gh, groupby='analysis_group', method='wilcoxon', use_raw=False)

# Get the top genes for our module
# We take the top 150 genes with a positive log-fold change
try:
    top_genes = sc.get.rank_genes_groups_df(adata_gh, group='Astro_Gfap_High')
    top_genes = top_genes[top_genes['logfoldchanges'] > 0.5]
    astro_gene_list = list(top_genes['names'].head(150))
    print(f"Found {len(astro_gene_list)} unique marker genes for the 'Astro_Gfap_High' Module.")
except KeyError:
    print("Could not find 'Astro_Gfap_High' in results. This can happen if no cells were in this group.")
    astro_gene_list = [] # Create an empty list

# --- 3. Run GO Enrichment on these genes ---
if len(astro_gene_list) > 10:
    print("Running GProfiler...")
    gp = GProfiler(return_dataframe=True)
    go_results = gp.profile(
        organism='mmusculus', # 'mmusculus' is for mouse
        query=astro_gene_list
    )

    # --- 4. Plot the Top 15 Results (like Kim Fig. 8) ---
    print("\n--- Top GO Enrichment Results for 'Astro_Gfap_High' Module ---")

    # Filter for just 'Biological Process' (GO:BP)
    go_bp = go_results[go_results['source'] == 'GO:BP'].head(15)

    if not go_bp.empty:
        # We plot the -log10(p-value) for better visualization
        go_bp['-log10_p_value'] = -np.log10(go_bp['p_value'])

        plt.figure(figsize=(10, 8))
        sns.barplot(
            data=go_bp,
            x='-log10_p_value',
            y='name',
            palette='viridis' # A nice color palette
        )
        plt.title("Top Biological Processes - 'Astro_Gfap_High' Module")
        plt.xlabel("-log10(p-value)")
        plt.ylabel("GO Term Name")
        plt.show()
    else:
        print("No GO:BP terms found.")
else:
    print("Not enough marker genes found to run GO enrichment.")

print("\n--- Functional Analysis Complete! ---")

"""# **Post Hoc Analysis: Differntial Gene Expression Analysis(Astro-DG)**"""

# --- CELL: ADVANCEMENT 4 - FINDING "FENCE" GENES (Robust Scipy Method) ---
import scanpy as sc
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from gprofiler import GProfiler
from scipy.spatial import KDTree # We will use this for distances

print("Running Advancement 4: Finding 'Repulsion' Interface Genes...")

# --- 1. Prepare the data ---
# We use 'adata_hip' which has all 95k cells
try:
    adata_hip.obs['subclass'] = adata_hip.obs['subclass'].astype('category')
except NameError:
    print("ERROR: 'adata_hip' not found. Please re-run all cells from Phase 2 to Phase 5 to recreate it.")
    raise

# Define our two groups
group_a = '037 DG Glut' # The neurons
group_b_types = [
    '319 Astro-TE NN',
    '318 Astro-NT NN',
    '321 Astroependymal NN',
    '320 Astro-OLF NN'
] # All astrocytes

# Create masks
is_group_a = adata_hip.obs['subclass'] == group_a
is_group_b = adata_hip.obs['subclass'].isin(group_b_types)

# --- 2. Calculate distance from every Astrocyte to the NEAREST DG Neuron ---
print("Calculating distances from Astrocytes to nearest DG Neuron using SciPy...")

# Get the 2D coordinates for Group A (DG Neurons)
coords_a = adata_hip[is_group_a].obsm['spatial']
# Get the 2D coordinates for Group B (Astrocytes)
coords_b = adata_hip[is_group_b].obsm['spatial']

# Build the KDTree (a fast search structure) on the neuron coordinates
tree_a = KDTree(coords_a)

# Query the tree: For each Astrocyte, find the distance to the single (k=1) nearest DG Neuron
# 'min_dists' will be an array of distances
min_dists, min_dist_indices = tree_a.query(coords_b, k=1)

print("Distance calculation complete.")

# --- 3. Create new groups: "Interface" vs "Distant" ---
# Get the IDs of the astrocytes
astro_ids = adata_hip.obs[is_group_b].index

# Create a new DataFrame with the distances
astro_dist_df = pd.DataFrame({'min_dist': min_dists}, index=astro_ids)

# Define "Interface" as the 25% of astrocytes closest to DG neurons
cutoff_25 = np.percentile(astro_dist_df['min_dist'], 25)

# Add this new group label to our main object
adata_hip.obs['astro_interface_group'] = 'Not_Astrocyte' # Default label
adata_hip.obs.loc[astro_dist_df.index, 'astro_interface_group'] = 'Distant_Astrocyte'
adata_hip.obs.loc[astro_dist_df[astro_dist_df['min_dist'] <= cutoff_25].index, 'astro_interface_group'] = 'Interface_Astrocyte'

# Convert to categorical
adata_hip.obs['astro_interface_group'] = adata_hip.obs['astro_interface_group'].astype('category')
print(f"Identified groups:\n{adata_hip.obs['astro_interface_group'].value_counts()}")

# --- 4. Run Differential Gene Expression (DGE) ---
print("\nRunning DGE: 'Interface' vs 'Distant' Astrocytes...")
sc.tl.rank_genes_groups(
    adata_hip,
    groupby='astro_interface_group',
    groups=['Interface_Astrocyte'],  # Find genes for this group...
    reference='Distant_Astrocyte', # ...compared to this group
    method='wilcoxon',
    use_raw=False
)

# --- 5. Plot a Volcano Plot (The DGE Result) ---
print("Plotting Volcano Plot...")
# Get the DGE results into a nice DataFrame
dge_results = sc.get.rank_genes_groups_df(adata_hip, group='Interface_Astrocyte')
dge_results['-log10_p_val'] = -np.log10(dge_results['pvals_adj'])

# Create the plot
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=dge_results,
    x='logfoldchanges',
    y='-log10_p_val',
    alpha=0.5
)
plt.title("Interface Astrocytes vs. Distant Astrocytes")
plt.xlabel("Log2 Fold Change")
plt.ylabel("-log10(Adjusted P-value)")

# Add labels for the top "fence genes"
top_genes = dge_results.nlargest(10, '-log10_p_val')
for i, row in top_genes.iterrows():
    plt.text(row['logfoldchanges'], row['-log10_p_val'], row['names'], fontsize=9)
plt.axhline(1.3, color='grey', linestyle='--') # p-value = 0.05
plt.axvline(0.5, color='grey', linestyle='--')
plt.axvline(-0.5, color='grey', linestyle='--')
plt.show()

# --- 6. Run GO Enrichment on the "Fence Genes" ---
print("\nRunning GO Enrichment on 'Fence Genes'...")

# Get the list of significant *upregulated* genes
fence_gene_list = list(dge_results[
    (dge_results['logfoldchanges'] > 0.5) &
    (dge_results['pvals_adj'] < 0.05)
]['names'])

print(f"Found {len(fence_gene_list)} 'Fence Genes'.")

if len(fence_gene_list) > 10:
    # Need to re-install this if the kernel was reset
    !pip install gprofiler-official
    from gprofiler import GProfiler

    gp = GProfiler(return_dataframe=True)
    go_results = gp.profile(
        organism='mmusculus',
        query=fence_gene_list
    )

    # Filter for 'Biological Process'
    go_bp = go_results[go_results['source'] == 'GO:BP'].head(15)

    if not go_bp.empty:
        go_bp['-log10_p_value'] = -np.log10(go_bp['p_value'])

        plt.figure(figsize=(10, 8))
        sns.barplot(
            data=go_bp,
            x='-log10_p_value',
            y='name',
            palette='Reds_r' # Use a Red palette
        )
        plt.title("Top Biological Processes - 'Fence Genes' (Interface Astrocytes)")
        plt.xlabel("-log10(p-value)")
        plt.ylabel("GO Term Name")
        plt.show()
    else:
        print("No GO:BP terms found for the fence genes.")
else:
    print("Not enough significant 'fence genes' found to run GO enrichment.")

print("\n--- Interface Gene Analysis Complete! ---")

"""# **Visual Confirmation of Fence Gene**"""

# --- CELL: ADVANCEMENT 5 - VISUAL CONFIRMATION (Corrected) ---
import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt

print("Running Advancement 5: Visual Confirmation of the 'Fence'...")

# --- 1. Plot the "Fence" (The Cell Groups) ---
# We use the 'adata_hip' object, which has your
# 'astro_interface_group' column from the last analysis.

try:
    adata_hip.obs
except NameError:
    print("ERROR: 'adata_hip' not found. Please re-run all cells from Phase 2 to Phase 5, and then Advancement 4.")
    raise

print("Plotting the 'Fence' map (Cell Groups)...")

# Define the groups we want to see
groups_to_plot = [
    '037 DG Glut',
    'Interface_Astrocyte',
    'Distant_Astrocyte'
]

# Create a mask to show only these cells
plot_mask = adata_hip.obs['astro_interface_group'].isin(groups_to_plot) | (adata_hip.obs['subclass'] == '037 DG Glut')
adata_fence_map = adata_hip[plot_mask, :].copy()

# We need to combine the 'subclass' and 'astro_interface_group' columns
adata_fence_map.obs['plot_group'] = adata_fence_map.obs['subclass'].astype(str)
# Overwrite astrocytes with our new labels
astro_mask = adata_fence_map.obs['astro_interface_group'].isin(['Interface_Astrocyte', 'Distant_Astrocyte'])
adata_fence_map.obs.loc[astro_mask, 'plot_group'] = adata_fence_map.obs.loc[astro_mask, 'astro_interface_group']
adata_fence_map.obs['plot_group'] = adata_fence_map.obs['plot_group'].astype('category')


# We use sq.pl.spatial_scatter for a clean plot
# --- 'show=False' argument removed ---
sq.pl.spatial_scatter(
    adata_fence_map,
    color="plot_group",
    shape=None,
    size=0.1,  # Make dots very small
    legend_loc="right", # Put legend on the side
    title="The 'Fence': DG Neurons vs. Interface Astrocytes"
)
# Show this plot immediately
plt.show()

# --- 2. Plot the "Fence Genes" (With individual titles) ---
print("\nPlotting the 'Fence Genes' (Gene Expression)...")

# These are the top genes from your volcano plot
fence_genes_to_plot = ['C1ql2', 'Lama3', 'Slc7a10', 'Thbs4']

# Create a figure with 1 row and 4 columns
fig, axes = plt.subplots(1, 4, figsize=(20, 5))

# Loop through each gene and plot it on its own axis
for i, gene in enumerate(fence_genes_to_plot):
    ax = axes[i] # Get the current axis
    # --- 'show=False' argument removed ---
    sq.pl.spatial_scatter(
        adata_hip, # Use the full 95k cohort
        color=gene,
        shape=None,
        size=0.1,
        cmap="viridis",
        ax=ax,
        title=f"Expression of {gene}" # Set individual title
    )

plt.tight_layout() # Make the plots fit nicely
plt.show()
# --- END OF FIX ---

print("\n--- Visual Confirmation Complete! ---")

"""# **Post Hoc Analysis: DGE ( Micro-DG)**"""

# --- CELL: ADVANCEMENT 4 - FINDING "FENCE" GENES (Corrected) ---

# --- THIS IS THE FIX ---
# We install the library first, before any imports
!pip install gprofiler-official
# --- CELL: ADVANCEMENT 4b - FINDING MICROGLIAL "FENCE" GENES ---
import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from gprofiler import GProfiler
from scipy.spatial import KDTree

print("Running Advancement 4b: Finding Microglial 'Repulsion' Interface Genes...")

# --- 1. Prepare the data ---
# We use 'adata_hip' which has all 95k cells
try:
    adata_hip.obs['subclass'] = adata_hip.obs['subclass'].astype('category')
except NameError:
    print("ERROR: 'adata_hip' not found. Please re-run all cells from Phase 2 to Phase 5 to recreate it.")
    raise

# Define our two groups
group_a = '037 DG Glut' # The neurons
# --- THIS IS THE MODIFIED LINE ---
group_b_types = [
    '334 Microglia NN'
] # All Microglia

# Create masks
is_group_a = adata_hip.obs['subclass'] == group_a
is_group_b = adata_hip.obs['subclass'].isin(group_b_types)

# --- 2. Calculate distance from every Microglia to the NEAREST DG Neuron ---
print("Calculating distances from Microglia to nearest DG Neuron using SciPy...")

# Get the 2D coordinates for Group A (DG Neurons)
coords_a = adata_hip[is_group_a].obsm['spatial']
# Get the 2D coordinates for Group B (Microglia)
coords_b = adata_hip[is_group_b].obsm['spatial']

# Build the KDTree (a fast search structure) on the neuron coordinates
tree_a = KDTree(coords_a)

# Query the tree: For each Microglia, find the distance to the single (k=1) nearest DG Neuron
min_dists, min_dist_indices = tree_a.query(coords_b, k=1)

print("Distance calculation complete.")

# --- 3. Create new groups: "Interface" vs "Distant" ---
# Get the IDs of the microglia
micro_ids = adata_hip.obs[is_group_b].index

# Create a new DataFrame with the distances
micro_dist_df = pd.DataFrame({'min_dist': min_dists}, index=micro_ids)

# Define "Interface" as the 25% of microglia closest to DG neurons
cutoff_25 = np.percentile(micro_dist_df['min_dist'], 25)

# Add this new group label to our main object
# We give it a UNIQUE name: 'micro_interface_group'
adata_hip.obs['micro_interface_group'] = 'Not_Microglia' # Default label
adata_hip.obs.loc[micro_dist_df.index, 'micro_interface_group'] = 'Distant_Microglia'
adata_hip.obs.loc[micro_dist_df[micro_dist_df['min_dist'] <= cutoff_25].index, 'micro_interface_group'] = 'Interface_Microglia'

# Convert to categorical
adata_hip.obs['micro_interface_group'] = adata_hip.obs['micro_interface_group'].astype('category')
print(f"Identified groups:\n{adata_hip.obs['micro_interface_group'].value_counts()}")

# --- 4. Run Differential Gene Expression (DGE) ---
print("\nRunning DGE: 'Interface' vs 'Distant' Microglia...")
sc.tl.rank_genes_groups(
    adata_hip,
    groupby='micro_interface_group',
    groups=['Interface_Microglia'],  # Find genes for this group...
    reference='Distant_Microglia', # ...compared to this group
    method='wilcoxon',
    use_raw=False
)

# --- 5. Plot a Volcano Plot (The DGE Result) ---
print("Plotting Volcano Plot...")
# Get the DGE results into a nice DataFrame
dge_results_micro = sc.get.rank_genes_groups_df(adata_hip, group='Interface_Microglia')
dge_results_micro['-log10_p_val'] = -np.log10(dge_results_micro['pvals_adj'])

# Create the plot
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=dge_results_micro,
    x='logfoldchanges',
    y='-log10_p_val',
    alpha=0.5
)
plt.title("Interface Microglia vs. Distant Microglia")
plt.xlabel("Log2 Fold Change")
plt.ylabel("-log10(Adjusted P-value)")

# Add labels for the top "fence genes"
top_genes = dge_results_micro.nlargest(10, '-log10_p_val')
for i, row in top_genes.iterrows():
    plt.text(row['logfoldchanges'], row['-log10_p_val'], row['names'], fontsize=9)
plt.axhline(1.3, color='grey', linestyle='--') # p-value = 0.05
plt.axvline(0.5, color='grey', linestyle='--')
plt.axvline(-0.5, color='grey', linestyle='--')
plt.show()

# --- 6. Run GO Enrichment on the "Fence Genes" ---
print("\nRunning GO Enrichment on Microglial 'Fence Genes'...")

# Get the list of significant *upregulated* genes
fence_gene_list_micro = list(dge_results_micro[
    (dge_results_micro['logfoldchanges'] > 0.5) &
    (dge_results_micro['pvals_adj'] < 0.05)
]['names'])

print(f"Found {len(fence_gene_list_micro)} 'Fence Genes' for Microglia.")

if len(fence_gene_list_micro) > 10:
    # We already installed gprofiler, so we can just import it
    from gprofiler import GProfiler

    gp = GProfiler(return_dataframe=True)
    go_results_micro = gp.profile(
        organism='mmusculus',
        query=fence_gene_list_micro
    )

    # Filter for 'Biological Process'
    go_bp_micro = go_results_micro[go_results_micro['source'] == 'GO:BP'].head(15)

    if not go_bp_micro.empty:
        go_bp_micro['-log10_p_value'] = -np.log10(go_bp_micro['p_value'])

        plt.figure(figsize=(10, 8))
        sns.barplot(
            data=go_bp_micro,
            x='-log10_p_value',
            y='name',
            palette='Reds_r' # Use a Red palette
        )
        plt.title("Top Biological Processes - 'Fence Genes' (Interface Microglia)")
        plt.xlabel("-log10(p-value)")
        plt.ylabel("GO Term Name")
        plt.show()
    else:
        print("No GO:BP terms found for the microglia fence genes.")
else:
    print("Not enough significant 'fence genes' found to run GO enrichment.")

print("\n--- Microglia Interface Gene Analysis Complete! ---")

"""# **GO Enrichment for Downregulated Gene**"""

# --- CELL: ADVANCEMENT 4c - GO ENRICHMENT FOR *DOWNREGULATED* GENES ---
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from gprofiler import GProfiler

print("\nRunning GO Enrichment on Microglial *Downregulated* 'Fence Genes'...")

# --- 1. Get the DGE results (already in memory) ---
# We use 'dge_results_micro' from the previous cell

# --- 2. Get the list of significant *DOWNREGULATED* genes ---
fence_gene_list_down = list(dge_results_micro[
    (dge_results_micro['logfoldchanges'] < -0.5) & # <-- Note the '<' sign
    (dge_results_micro['pvals_adj'] < 0.05)
]['names'])

print(f"Found {len(fence_gene_list_down)} 'Silenced Genes' for Microglia.")

if len(fence_gene_list_down) > 10:
    gp = GProfiler(return_dataframe=True)
    go_results_down = gp.profile(
        organism='mmusculus',
        query=fence_gene_list_down
    )

    # Filter for 'Biological Process'
    go_bp_down = go_results_down[go_results_down['source'] == 'GO:BP'].head(15)

    if not go_bp_down.empty:
        go_bp_down['-log10_p_value'] = -np.log10(go_bp_down['p_value'])

        plt.figure(figsize=(10, 8))
        sns.barplot(
            data=go_bp_down,
            x='-log10_p_value',
            y='name',
            palette='Blues_r' # Use a Blue palette
        )
        plt.title("Top Biological Processes - 'Silenced Genes' (Interface Microglia)")
        plt.xlabel("-log10(p-value)")
        plt.ylabel("GO Term Name")
        plt.show()
    else:
        print("No GO:BP terms found for the microglia silenced genes.")
else:
    print("Not enough significant 'silenced genes' found to run GO enrichment.")

print("\n--- Microglia Silencing Analysis Complete! ---")

"""# **Post Hoc Analysis: DGE ( Micro- Astro)**"""

# --- CELL: ADVANCEMENT 6 - FINDING "ASTROCYTE-MICROGLIA" ATTRACTION GENES ---
import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from gprofiler import GProfiler
from scipy.spatial import KDTree

print("Running Advancement 6: Finding 'Astrocyte-Microglia' Interface Genes...")

# --- 1. Prepare the data ---
# We use 'adata_hip' which has all 95k cells
try:
    adata_hip.obs['subclass'] = adata_hip.obs['subclass'].astype('category')
except NameError:
    print("ERROR: 'adata_hip' not found. Please re-run all cells from Phase 2 to Phase 5 to recreate it.")
    raise

# --- DEFINE OUR NEW GROUPS ---
# Group A = All Microglia
group_a = '334 Microglia NN'
# Group B = All Astrocytes
group_b_types = [
    '319 Astro-TE NN',
    '318 Astro-NT NN',
    '321 Astroependymal NN',
    '320 Astro-OLF NN'
]

# Create masks
is_group_a = adata_hip.obs['subclass'] == group_a
is_group_b = adata_hip.obs['subclass'].isin(group_b_types)

# --- 2. Calculate distance from every Astrocyte to the NEAREST Microglia ---
print("Calculating distances from Astrocytes to nearest Microglia using SciPy...")

# Get the 2D coordinates for Group A (Microglia)
coords_a = adata_hip[is_group_a].obsm['spatial']
# Get the 2D coordinates for Group B (Astrocytes)
coords_b = adata_hip[is_group_b].obsm['spatial']

# Build the KDTree (a fast search structure) on the microglia coordinates
tree_a = KDTree(coords_a)

# Query the tree: For each Astrocyte, find the distance to the single (k=1) nearest Microglia
min_dists, min_dist_indices = tree_a.query(coords_b, k=1)

print("Distance calculation complete.")

# --- 3. Create new groups: "Interface" vs "Distant" Astrocytes ---
# Get the IDs of the astrocytes
astro_ids = adata_hip.obs[is_group_b].index

# Create a new DataFrame with the distances
astro_dist_df = pd.DataFrame({'min_dist_to_microglia': min_dists}, index=astro_ids)

# Define "Interface" as the 25% of astrocytes closest to microglia
cutoff_25 = np.percentile(astro_dist_df['min_dist_to_microglia'], 25)

# Add this new group label to our main object
adata_hip.obs['astro_micro_interface_group'] = 'Not_Astrocyte' # Default label
adata_hip.obs.loc[astro_dist_df.index, 'astro_micro_interface_group'] = 'Distant_Astro_from_Micro'
adata_hip.obs.loc[astro_dist_df[astro_dist_df['min_dist_to_microglia'] <= cutoff_25].index, 'astro_micro_interface_group'] = 'Interface_Astro_to_Micro'

# Convert to categorical
adata_hip.obs['astro_micro_interface_group'] = adata_hip.obs['astro_micro_interface_group'].astype('category')
print(f"Identified groups:\n{adata_hip.obs['astro_micro_interface_group'].value_counts()}")

# --- 4. Run Differential Gene Expression (DGE) ---
print("\nRunning DGE: 'Interface' vs 'Distant' Astrocytes...")
sc.tl.rank_genes_groups(
    adata_hip,
    groupby='astro_micro_interface_group',
    groups=['Interface_Astro_to_Micro'],  # Find genes for this group...
    reference='Distant_Astro_from_Micro', # ...compared to this group
    method='wilcoxon',
    use_raw=False
)

# --- 5. Plot a Volcano Plot (The DGE Result) ---
print("Plotting Volcano Plot...")
# Get the DGE results into a nice DataFrame
dge_results_am = sc.get.rank_genes_groups_df(adata_hip, group='Interface_Astro_to_Micro')
dge_results_am['-log10_p_val'] = -np.log10(dge_results_am['pvals_adj'])

# Create the plot
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=dge_results_am,
    x='logfoldchanges',
    y='-log10_p_val',
    alpha=0.5
)
plt.title("Interface Astrocytes (near Microglia) vs. Distant Astrocytes")
plt.xlabel("Log2 Fold Change")
plt.ylabel("-log10(Adjusted P-value)")

# Add labels for the top "attraction genes"
top_genes = dge_results_am.nlargest(10, '-log10_p_val')
for i, row in top_genes.iterrows():
    plt.text(row['logfoldchanges'], row['-log10_p_val'], row['names'], fontsize=9)
plt.axhline(1.3, color='grey', linestyle='--') # p-value = 0.05
plt.axvline(0.5, color='grey', linestyle='--')
plt.axvline(-0.5, color='grey', linestyle='--')
plt.show()

# --- 6. Run GO Enrichment on the "Attraction Genes" ---
print("\nRunning GO Enrichment on 'Attraction Genes'...")

# Get the list of significant *upregulated* genes
attraction_gene_list = list(dge_results_am[
    (dge_results_am['logfoldchanges'] > 0.5) &
    (dge_results_am['pvals_adj'] < 0.05)
]['names'])

print(f"Found {len(attraction_gene_list)} 'Attraction Genes'.")

if len(attraction_gene_list) > 10:
    # We already installed gprofiler
    from gprofiler import GProfiler

    gp = GProfiler(return_dataframe=True)
    go_results_am = gp.profile(
        organism='mmusculus',
        query=attraction_gene_list
    )

    # Filter for 'Biological Process'
    go_bp_am = go_results_am[go_results_am['source'] == 'GO:BP'].head(15)

    if not go_bp_am.empty:
        go_bp_am['-log10_p_value'] = -np.log10(go_bp_am['p_value'])

        plt.figure(figsize=(10, 8))
        sns.barplot(
            data=go_bp_am,
            x='-log10_p_value',
            y='name',
            palette='Greens_r' # Use a Green palette
        )
        plt.title("Top Biological Processes - 'Attraction Genes' (Interface Astrocytes)")
        plt.xlabel("-log10(p-value)")
        plt.ylabel("GO Term Name")
        plt.show()
    else:
        print("No GO:BP terms found for the attraction genes.")
else:
    print("Not enough significant 'attraction genes' found to run GO enrichment.")

print("\n--- Astrocyte-Microglia Interface Analysis Complete! ---")

"""# **Network Graph**"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np # Import numpy

# 1. Install and import new plotting libraries
print("Installing plotting libraries (if needed)...")
!pip install holoviews bokeh
import holoviews as hv
from holoviews import opts
from IPython.display import display
hv.extension('bokeh')

print("Plotting Network Graph (Chord Diagram) using HoloViews...")

# --- 2. Get the Z-score DataFrame (from previous steps) ---
try:
    results_key = "subclass_nhood_enrichment"
    enrichment_results = adata_final.uns[results_key]
    z_scores = enrichment_results['zscore'] # This is the NumPy array
    category_names = list(adata_final.obs['subclass'].cat.categories)

    # Convert the numpy array to a labeled pandas DataFrame
    z_score_df = pd.DataFrame(z_scores, index=category_names, columns=category_names)

    # Clean the DataFrame (like we did for the clustermap)
    z_score_df.fillna(0, inplace=True)
    z_score_df.replace([np.inf, -np.inf], 0, inplace=True)

except NameError:
    print("ERROR: 'adata_final' not found. Please re-run the '# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---' cell first.")
    raise
except KeyError:
    print("ERROR: 'subclass_nhood_enrichment' results not found. Please re-run the '# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---' cell first.")
    raise

# --- 3. Convert DataFrame to "long format" for HoloViews ---
chord_data = z_score_df.stack().reset_index()
chord_data.columns = ['source', 'target', 'z_score']

# --- 4. Filter the data for a cleaner plot ---
# Remove self-loops (e.g., Astro vs Astro)
chord_data = chord_data[chord_data['source'] != chord_data['target']]
# Filter for significant interactions (Z-score > 2 or < -2)
chord_data = chord_data[np.abs(chord_data['z_score']) > 2.0]

if chord_data.empty:
    print("No significant interactions found to plot (|Z-score| > 2.0).")
else:
    # --- 5. Create the Chord Diagram ---
    print("Plotting...")

    # Create the Chord object
    chord = hv.Chord(chord_data)

    # --- THIS IS THE CORRECTED OPTION ---
    # We explicitly tell it to use the 'index' of the nodes for both
    # the labels and the node colors.
    chord.opts(
        opts.Chord(
            cmap='coolwarm',          # Colormap for the edges
            edge_color='z_score',     # The column to use for edge color
            node_color='index',       # Color nodes by their name (index)
            node_cmap='Category20',   # Colormap for the nodes
            labels='index',           # Use the 'index' (the cell type name) for labels
            width=600,
            height=600,
            title="Hippocampal Niche Interactions (Chord Diagram, |Z| > 2.0)"
        )
    )

    display(chord) # This will render the interactive plot

print("\n--- Network Graph Complete! ---")

# --- SAVE INTERACTIVE PLOT ---
import holoviews as hv
from google.colab import files

print("Saving interactive Chord Diagram...")

# 1. Save the 'chord' object to an HTML file
# 'chord' is the variable name from our previous cell
hv.save(chord, 'interactive_chord_diagram.html')

# 2. Download it to your computer
files.download('interactive_chord_diagram.html')

import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt

print("Running Advancement 7: Predicting Cell-Cell Communication...")

# --- 1. Check if adata_final is in memory ---
try:
    # We check for the 'nhood_enrichment' key as a proxy
    adata_final.uns['subclass_nhood_enrichment']
except NameError:
    print("ERROR: 'adata_final' not found. Please re-run the '# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---' cell first.")
    raise
except KeyError:
     print("ERROR: 'adata_final' is in memory, but the enrichment results are missing. Please re-run the '# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---' cell first.")
     raise

# --- 2. Run the Ligand-Receptor Interaction Analysis ---
# This re-uses the calculation from your previous attempt if it exists
if 'ligrec' not in adata_final.uns:
    print("Calculating Ligand-Receptor interactions... (This may take a moment)")
    sq.gr.ligrec(
        adata_final,
        n_perms=100, # Set to a positive value for permutation testing
        cluster_key="subclass",
        use_raw=False
    )
else:
    print("Using existing Ligand-Receptor calculation...")

# --- 3. Plot the Results (Chord Diagram for ALL interactions) ---
print("\nPlotting Figure 1: Total L-R Interactions (All Cell Types)")
try:
    sq.pl.ligrec(
        adata_final,
        cluster_key="subclass",
        # We REMOVED 'source_groups' to plot EVERYTHING
        show=False,
        title="Total L-R Interactions (All Cell Types)"
    )
    plt.show()
except ValueError as e:
    print(f"\n--- PLOTTING ERROR ---")
    print(f"Error: {e}")
    print("This likely means NO significant interactions (p < 0.05) were found in the ENTIRE dataset.")
    print("This is possible due to the limited 1122-gene panel.")

print("Creating 'Targeted Mechanism Plot' for slides...")

# 1. Retrieve the L-R analysis results
# The results are stored in these DataFrames inside the object
try:
    means_df = adata_final.uns['ligrec']['means']
    pvals_df = adata_final.uns['ligrec']['pvalues']
except KeyError:
    print("ERROR: Ligand-Receptor results not found. Please re-run 'Cell 7A'.")
    raise

# 2. Define the "Fence Genes" we want to highlight
# We look for pathways where these genes are the LIGAND (Sender)
fence_genes = ['C1ql2', 'Tnc', 'Lama3', 'Slc7a10']

# 3. Define the Cell Pairs we care about
# We want to see signals FROM Astrocytes/Microglia TO Neurons/Glia
relevant_sources = ['319 Astro-TE NN', '334 Microglia NN']
relevant_targets = ['037 DG Glut', '334 Microglia NN', '319 Astro-TE NN']

# 4. Filter the Data
# Step A: Filter Columns (Cell Pairs)
selected_cols = []
for col in means_df.columns:
    source, target = col.split(' | ') # Squidpy format: "Source | Target"
    if source in relevant_sources and target in relevant_targets:
        selected_cols.append(col)

filtered_means = means_df[selected_cols]
filtered_pvals = pvals_df[selected_cols]

# Step B: Filter Rows (Gene Pathways)
# We keep rows where the interaction name includes one of our fence genes
selected_rows = []
for interaction in filtered_means.index:
    # interaction string format: "Ligand_Receptor"
    for gene in fence_genes:
        if gene in interaction:
            selected_rows.append(interaction)
            break # Found a match, keep this row

if not selected_rows:
    print("WARNING: No interactions found for your specific fence genes in the L-R results.")
    print("This might be due to the limited gene panel (1122 genes).")
    print("Plotting top 10 strongest interactions instead for demonstration.")
    # Fallback: Take top 10 interactions by max mean expression
    selected_rows = filtered_means.max(axis=1).nlargest(10).index.tolist()

final_means = filtered_means.loc[selected_rows]
final_pvals = filtered_pvals.loc[selected_rows]

# 5. Plot the Dot Plot
# We prepare data for plotting
# X axis: Cell Pairs, Y axis: Gene Pairs
# Size: Significance (-log p-value), Color: Strength (Mean)

# Reshape for plotting
plot_data = final_means.stack().reset_index()
plot_data.columns = ['Interaction', 'Cell_Pair', 'Mean_Expression']
plot_data['P_Value'] = final_pvals.stack().values
plot_data['-Log10_P'] = -np.log10(plot_data['P_Value'] + 1e-5) # Avoid log(0)

# Create the plot
plt.figure(figsize=(8, 6)) # Standard slide aspect ratio
scatter = sns.scatterplot(
    data=plot_data,
    x='Cell_Pair',
    y='Interaction',
    size='-Log10_P',     # Dot size = Significance
    hue='Mean_Expression', # Dot color = Strength
    sizes=(20, 400),     # Range of dot sizes
    palette='viridis',
    edgecolor='black'
)

plt.title("Mechanism: Fence Gene Signaling Pathways", fontsize=14)
plt.xticks(rotation=45, ha='right') # Rotate labels to fit
plt.xlabel("")
plt.ylabel("Ligand-Receptor Pair")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Significance & Strength")

plt.tight_layout()
plt.show()

print("\n--- Slide-Ready Plot Generated! ---")

# --- CELL 7B: L-R ANALYSIS (SPECIFIC DOT PLOT) ---
import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt

print("\nPlotting Figure 2: Specific L-R Pathway Dot Plot (All p-values)")

try:
    # Let's see the interactions between Astrocytes and Microglia
    sq.pl.ligrec(
        adata_final,
        cluster_key="subclass",
        source_groups="319 Astro-TE NN",  # Sender
        target_groups="334 Microglia NN",  # Receiver
        means_range=(0.01, 10.0), # Use a broad expression range
        alpha=1.0, # Set p-value cutoff to 1.0 to show EVERYTHING
        swap_axes=True, # Put pathways on the Y-axis
        title="Potential L-R Pathways: Astrocytes -> Microglia (All p-values)"
    )
    plt.show()

except ValueError as e:
    print(f"\n--- PLOTTING ERROR ---")
    print(f"Error: {e}")
    print("This confirms that no L-R pairs were found between these two specific groups,")
    print("likely due to the limited gene panel.")

print("\n--- Ligand-Receptor Analysis Complete! ---")

# --- IN YOUR *FIRST* NOTEBOOK (Corrected Save Cell v3) ---
import anndata as ad
import scanpy as sc

print("Creating a new, clean object to save...")

# This assumes 'adata_final' is your 65,956-cell object
try:
    # 1. Create a new, empty AnnData object
    adata_to_save = ad.AnnData(
        X=adata_final.X,
        obs=adata_final.obs,
        var=adata_final.var,
        obsm=adata_final.obsm
    )

    # 2. Save the new, clean object
    adata_to_save.write_h5ad("healthy_blueprint_data.h5ad")

    print("\nFile 'healthy_blueprint_data.h5ad' saved successfully.")
    print("This file contains all the data needed for the AI project.")
    print("You can now download it from the file browser on the left (you may need to refresh the browser).")

except NameError:
    print("\n--- ERROR ---")
    print("'adata_final' not found. Please re-run your main analysis cell ('# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---') to create it again.")
except Exception as e:
    print(f"\nAn error occurred during saving: {e}")



"""# Task
Modify cell `J7_zrxY3VOFg` to include `alpha=1.0` in the `sq.gr.ligrec` function call, then re-run cell `J7_zrxY3VOFg`, followed by executing cell `Qv43SoBo9R4i` and cell `I3PhlzrHWaH7` to resolve the `KeyError` and generate the ligand-receptor analysis plots.

## Modify Ligand-Receptor Analysis to always populate results

### Subtask:
Modify cell `J7_zrxY3VOFg` to include `alpha=1.0` in the `sq.gr.ligrec` function call. This ensures that the `'ligrec'` key in `adata_final.uns` is always populated with all computed ligand-receptor interactions, preventing `KeyError` in subsequent cells, even if no statistically significant interactions are found at default alpha.

**Reasoning**:
The subtask requires modifying cell `J7_zrxY3VOFg` to include `alpha=1.0` in the `sq.gr.ligrec` function call to ensure consistent population of results.
"""

import squidpy as sq
import scanpy as sc
import matplotlib.pyplot as plt

print("Running Advancement 7: Predicting Cell-Cell Communication...")

# --- 1. Check if adata_final is in memory ---
try:
    # We check for the 'nhood_enrichment' key as a proxy
    adata_final.uns['subclass_nhood_enrichment']
except NameError:
    print("ERROR: 'adata_final' not found. Please re-run the '# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---' cell first.")
    raise
except KeyError:
     print("ERROR: 'adata_final' is in memory, but the enrichment results are missing. Please re-run the '# --- Combined Cell: Analysis & Z-Score Extraction (FINAL) ---' cell first.")
     raise

# --- 2. Run the Ligand-Receptor Interaction Analysis ---
# This re-uses the calculation from your previous attempt if it exists
if 'ligrec' not in adata_final.uns:
    print("Calculating Ligand-Receptor interactions... (This may take a moment)")
    sq.gr.ligrec(
        adata_final,
        n_perms=100, # Set to a positive value for permutation testing
        cluster_key="subclass",
        use_raw=False,
        alpha=1.0 # Added to always populate results
    )
else:
    print("Using existing Ligand-Receptor calculation...")

# --- 3. Plot the Results (Chord Diagram for ALL interactions) ---
print("\nPlotting Figure 1: Total L-R Interactions (All Cell Types)")
try:
    sq.pl.ligrec(
        adata_final,
        cluster_key="subclass",
        # We REMOVED 'source_groups' to plot EVERYTHING
        show=False,
        title="Total L-R Interactions (All Cell Types)"
    )
    plt.show()
except ValueError as e:
    print(f"\n--- PLOTTING ERROR ---")
    print(f"Error: {e}")
    print("This likely means NO significant interactions (p < 0.05) were found in the ENTIRE dataset.")
    print("This is possible due to the limited 1122-gene panel.")

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.image as mpimg

# 1. Load your Chord Diagram Image
try:
    img = mpimg.imread('bokeh_plot.png')
except FileNotFoundError:
    print("Error: 'bokeh_plot.png' not found. Please check file name.")
    raise

# 2. Create the Slide Layout
fig, ax = plt.subplots(figsize=(16, 9))
ax.set_xlim(0, 16)
ax.set_ylim(0, 9)
ax.axis('off')

# --- ADD THE IMAGE (LEFT SIDE) ---
ax.imshow(img, extent=[0.5, 8.5, 1.5, 8.5], aspect='auto')

# --- ADD THE TITLE ---
ax.text(8, 8.5, "A New Baseline for Disease & A Model for African Science",
        fontsize=24, fontweight='bold', ha='center', color='#2C3E50')

# --- ADD THE ANNOTATIONS (Triangle Concept) ---
ax.annotate("The Fence: Active Repulsion\n(Genes: TNC, C1QL2)",
            xy=(4.5, 5.5), xycoords='data',
            xytext=(1.0, 7.0), textcoords='data',
            arrowprops=dict(arrowstyle="->", color='blue', lw=2),
            fontsize=12, fontweight='bold', color='blue',
            bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="blue", alpha=0.9))

ax.annotate("The Hub: Neurogenic Support\n(Glia-Glia Attraction)",
            xy=(4.5, 3.5), xycoords='data',
            xytext=(1.0, 2.0), textcoords='data',
            arrowprops=dict(arrowstyle="->", color='red', lw=2),
            fontsize=12, fontweight='bold', color='#C0392B',
            bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#C0392B", alpha=0.9))

# --- ADD THE MESSAGE (RIGHT SIDE) ---
# We build the text string using + to mix normal strings (with \n) and raw strings (for bolding)

text_content = (
    "1. " + r"$\bf{The\ Scientific\ Discovery}$" + ":\n"
    "   • The healthy hippocampus is defined by an active\n"
    "     'Glial-Neuronal Fence' that protects neurogenesis.\n"
    "   " + r"$\bf{Mechanism}$" + ": Built by TNC and C1QL2.\n"
    "   " + r"$\bf{Insight}$" + ": Disease (AD, Epilepsy) likely begins when\n"
    "     this specific fence breaks.\n\n"
    "2. " + r"$\bf{The\ Strategic\ Impact}$" + ":\n"
    "   • First quantitative baseline to measure early\n"
    "     glial infiltration.\n\n"
    "3. " + r"$\bf{Capacity\ Building\ in\ Africa}$" + ":\n"
    "   • Demonstrates the power of open-access data\n"
    "     (Allen Institute) for high-impact research.\n"
    "   • Proves that African students can contribute " + r"$\bf{novel}$" + "\n"
    "     " + r"$\bf{findings}$" + " even in limited-resource settings.\n"
    "   • Overcoming infrastructure barriers with\n"
    "     computational innovation."
)

ax.text(8.8, 5.0, text_content, fontsize=15, va='center', ha='left',
        bbox=dict(boxstyle="round,pad=1", fc="#ECF0F1", ec="none"))

# --- SAVE THE SLIDE ---
plt.savefig("Slide_10_Conclusion_Final.png", dpi=300, bbox_inches='tight')
plt.show()

print("Slide generated! Download 'Slide_10_Conclusion_Final.png'")
